// <auto-generated />
using Final_Project_ITI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project_ITI.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Project_ITI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptName = "SOC"
                        },
                        new
                        {
                            Id = 2,
                            DeptName = "Asp .NET"
                        },
                        new
                        {
                            Id = 3,
                            DeptName = "IS"
                        },
                        new
                        {
                            Id = 4,
                            DeptName = "Laravel"
                        },
                        new
                        {
                            Id = 5,
                            DeptName = "Cyber Security"
                        },
                        new
                        {
                            Id = 6,
                            DeptName = "CS"
                        },
                        new
                        {
                            Id = 7,
                            DeptName = "Front-End"
                        });
                });

            modelBuilder.Entity("Final_Project_ITI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cleopatra's Needle",
                            Age = 20,
                            DeptId = 3,
                            Email = "omaraahmed00@example.com",
                            Name = "omar",
                            Password = "opoppoop"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bold Street",
                            Age = 25,
                            DeptId = 2,
                            Email = "ahmedomar@example.com",
                            Name = "ahmed",
                            Password = "mkimki"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kensington High Street",
                            Age = 26,
                            DeptId = 1,
                            Email = "zizoali@example.com",
                            Name = "ziad",
                            Password = "mekky00"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Covent Garden",
                            Age = 20,
                            DeptId = 4,
                            Email = "mousa@example.com",
                            Name = "osman",
                            Password = "00mekky"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Station Road",
                            Age = 18,
                            DeptId = 6,
                            Email = "osman@example.com",
                            Name = "ali",
                            Password = "me00kky"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Church Lane",
                            Age = 22,
                            DeptId = 5,
                            Email = "diaa@example.com",
                            Name = "diaa",
                            Password = "mekk00y"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Jude Street",
                            Age = 32,
                            DeptId = 7,
                            Email = "zidan@example.com",
                            Name = "Zidan",
                            Password = "mek00ky"
                        });
                });

            modelBuilder.Entity("Final_Project_ITI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "omaraahmed7@example.com",
                            Name = "omar",
                            Password = "99999999"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marawan@example.com",
                            Name = "marawan",
                            Password = "00000000"
                        });
                });

            modelBuilder.Entity("Final_Project_ITI.Models.Student", b =>
                {
                    b.HasOne("Final_Project_ITI.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Final_Project_ITI.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
