// <auto-generated />
using System;
using Students_Education_Platform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Students_Education_Platform.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20260602233209_V_4")]
    partial class V_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Students_Education_Platform.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "OOP",
                            DeptId = 2,
                            Duration = 40
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Database & SQL",
                            DeptId = 3,
                            Duration = 36
                        },
                        new
                        {
                            Id = 3,
                            CourseName = ".Net Basics",
                            DeptId = 4,
                            Duration = 30
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Network Security",
                            DeptId = 5,
                            Duration = 45
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "HTML & CSS & JS",
                            DeptId = 7,
                            Duration = 50
                        });
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptName = "SOC"
                        },
                        new
                        {
                            Id = 2,
                            DeptName = "Asp .NET"
                        },
                        new
                        {
                            Id = 3,
                            DeptName = "IS"
                        },
                        new
                        {
                            Id = 4,
                            DeptName = "Laravel"
                        },
                        new
                        {
                            Id = 5,
                            DeptName = "Cyber Security"
                        },
                        new
                        {
                            Id = 6,
                            DeptName = "CS"
                        },
                        new
                        {
                            Id = 7,
                            DeptName = "Front-End"
                        });
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FullMark")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Date = new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FullMark = 100,
                            Title = "OOP Final Exam"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Date = new DateTime(2025, 6, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FullMark = 50,
                            Title = "SQL Practical Exam"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Date = new DateTime(2025, 6, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FullMark = 20,
                            Title = "Laravel Basic Quiz"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Date = new DateTime(2025, 6, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FullMark = 100,
                            Title = "Network Security Midterm"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Date = new DateTime(2025, 6, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FullMark = 100,
                            Title = "Front-End Integration Test"
                        });
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cleopatra's Needle",
                            Age = 20,
                            DeptId = 3,
                            Email = "omaraahmed00@example.com",
                            Name = "omar",
                            Password = "opoppoop"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bold Street",
                            Age = 25,
                            DeptId = 2,
                            Email = "ahmedomar@example.com",
                            Name = "ahmed",
                            Password = "mkimki"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kensington High Street",
                            Age = 26,
                            DeptId = 1,
                            Email = "zizoali@example.com",
                            Name = "ziad",
                            Password = "mekky00"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Covent Garden",
                            Age = 20,
                            DeptId = 4,
                            Email = "mousa@example.com",
                            Name = "osman",
                            Password = "00mekky"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Station Road",
                            Age = 18,
                            DeptId = 6,
                            Email = "osman@example.com",
                            Name = "ali",
                            Password = "me00kky"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Church Lane",
                            Age = 22,
                            DeptId = 5,
                            Email = "diaa@example.com",
                            Name = "diaa",
                            Password = "mekk00y"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Jude Street",
                            Age = 32,
                            DeptId = 7,
                            Email = "zidan@example.com",
                            Name = "Zidan",
                            Password = "mek00ky"
                        });
                });

            modelBuilder.Entity("Students_Education_Platform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "omaraahmed7@example.com",
                            Name = "omar",
                            Password = "99999999"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marawan@example.com",
                            Name = "marawan",
                            Password = "00000000"
                        });
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Course", b =>
                {
                    b.HasOne("Students_Education_Platform.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Exam", b =>
                {
                    b.HasOne("Students_Education_Platform.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Student", b =>
                {
                    b.HasOne("Students_Education_Platform.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Course", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Students_Education_Platform.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
